### ISSUE TITLE
Why is the number of images in 'json' file greater than in image folder?

### ISSUE THREAD

**Issue by KeplerWang** [sartorius-research/LIVECell#14]
Hi! Thanks for your great works and code repo.

I'm new in Cell Segmentation and going to reproduce your work as a part of my graduation projects. I'm a liitle confused after loading the `livecell_coco_{train/val/test}.json`. Below is the detail code.

```python
from pycocotools.coco import COCO

coco = COCO('livecell_coco_test.json')
test_ids = coco.getImgIds()
print(len(test_ids))
# 1564 for test
# 570 for val
# 3253 for train

import os
test_imgs = os.listdir('test_images')
print(len(test_imgs))
# 1512 for test < 1564
# 3727 for trainval < 3253 + 570

```
Note: The `json` and `images` data download from your repo [Github website](https://sartorius-research.github.io/LIVECell/), `LIVECell-wide train and evaluate` and `How to access LIVECell`, repectively. Maybe I have renamed the image folder names, but it doesn't matter. :>

It seems that one image in `{trainval/test}_images` may get more than one imgae `ids` in `livecell_coco_{train/val/test}.json`. 

Is that true? Could you please help explain it? :)

**Comment by ChristofferEdlund** [comment]
Dear @KeplerWang, thank you for those kind words and for your interest in our work.

As stated in our[paper](https://www.nature.com/articles/s41592-021-01249-6)there is a number of images that got annotated twice due to annotation error. Each duplicate annotation will then have its own reference to the same image.

Instead of pruning the annotations we selected to keep both versions and disclose which image that has dual annotations, as can be seen in our [supplementary table](https://www.nature.com/articles/s41592-021-01249-6#Sec27).

I hope this is the information you where looking for, let me know if there is any other issues.

Kindly,
Christoffer

**Comment by KeplerWang** [comment]
> Dear @KeplerWang, thank you for those kind words and for your interest in our work.
> 
> As stated in our[paper](https://www.nature.com/articles/s41592-021-01249-6)there is a number of images that got annotated twice due to annotation error. Each duplicate annotation will then have its own reference to the same image.
> 
> Instead of pruning the annotations we selected to keep both versions and disclose which image that has dual annotations, as can be seen in our [supplementary table](https://www.nature.com/articles/s41592-021-01249-6#Sec27).
> 
> I hope this is the information you where looking for, let me know if there is any other issues.
> 
> Kindly, Christoffer

I see! Thanks, @ChristofferEdlund.
