### ISSUE TITLE
IndexError during evaluation with coco_evaluation_resnest.py

### ISSUE THREAD

**Issue by hellebe** [sartorius-research/LIVECell#15]
Hello and thanks for your interesting work!

When evaluating your Anchor-based model with coco_evaluation_resnest.py, I get an error saying:

**"IndexError: too many indices for array: array is 4-dimensional, but 5 were indexed"** for line 657 in coco_evaluation_resnest.py **rec_pre_iou = [recalls[iou_idx, :, :, 0, -1].mean() for iou_idx in range(recalls.shape[0])]**.

Seems like pycocotools returns "**recall = -np.ones((T,K,A,M))**" in cocoeval.py and therefore only 4 indices are given instead of 5 like in "**precision = -np.ones((T,R,K,A,M))**". Removing the second index in "**rec_pre_iou = [recalls[iou_idx, :, :, 0, -1].mean()**" seems to do the job.

Can you maybe reproduce the error and tell me, if the solution for this bug is correct?

Thanks in advance!

**Comment by ChristofferEdlund** [comment]
Hi there @hellebe, 

Could you try to download a python package called [fast-coco-eval](https://pypi.org/project/fast-coco-eval/) and see if this API together with the coco_evaluation_resnest.py evaluation script fixes your problem?

`pip install fast-coco-eval`

If you have not done any changes to the evaluation script, it should work out-of-the-box with fast-coco-eval if you have it installed.

kindly,
Christoffer

**Comment by ChristofferEdlund** [comment]
@hellebe further update:

I have recreated the environment and it is indeed a bug as you eluded to. The coco_evaluation_resnest script has been updated and the fix is to change:

` rec_pre_iou = [recalls[iou_idx, :, :, 0, -1].mean() for iou_idx in range(recalls.shape[0])]`

to:

` rec_pre_iou = [recalls[iou_idx, :, 0, -1].mean() for iou_idx in range(recalls.shape[0])]`

This was already the case in the other evluation script we provided so the bug was only present in the resnest version. 
Thank you pointing it out!
