### ISSUE TITLE
Why the number of classes is 1?

### ISSUE THREAD

**Issue by YHPeter** [sartorius-research/LIVECell#7]

**Comment by ChristofferEdlund** [comment]
Hi there @YHPeter, thank you for your interest in the LIVECell dataset. We only have once class since the experiments only set out to do instance segmentation on cells and we only have one class - cells.  

Hope that answered your question,

Kindly,
Christoffer

**Comment by YHPeter** [comment]
Is there any difference in score to set several smaller categories? Thanks!

**Comment by RickardSjogren** [comment]
The score reported in the paper is calculated using only one class of instances. It is possible that you achieve better segmentation performance by training with several categories instead of one. Although, if you want the score to be comparable to the ones reported in the paper you need to convert your predictions back to one class before evaluating.

**Comment by YHPeter** [comment]
Understand now! Thanks!
